export const REGISTRY: Record<string, string> = {
  'accordion':         'accordion',
  'action-sheet':      'action-sheet',
  'alert':             'alert',
  'alert-dialog':      'alert-dialog',
  'avatar':            'avatar',
  'badge':             'badge',
  'balance-card':      'balance-card',
  'bank-transfer-form':'bank-transfer-form',
  'bottom-sheet':      'bottom-sheet',
  'button':            'button',
  'card':              'card',
  'carousel':          'carousel',
  'checkbox':          'checkbox',
  'collapsible':       'collapsible',
  'color-picker':      'color-picker',
  'combobox':          'combobox',
  'confirm-sheet':     'confirm-sheet',
  'crypto-amount-input':'crypto-amount-input',
  'date-picker':       'date-picker',
  'input':             'input',
  'input-otp':         'input-otp',
  'picker':            'picker',
  'popover':           'popover',
  'progress':          'progress',
  'qr-scanner':        'qr-scanner',
  'radio':             'radio',
  'receipt-card':      'receipt-card',
  'searchbar':         'searchbar',
  'select-bank-sheet': 'select-bank-sheet',
  'separator':         'separator',
  'service-grid':      'service-grid',
  'sheet':             'sheet',
  'skeleton':          'skeleton',
  'spinner':           'spinner',
  'success-screen':    'success-screen',
  'switch':            'switch',
  'table':             'table',
  'tabs':              'tabs',
  'text':              'text',
  'toast':             'toast',
  'toggle':            'toggle',
  'token-badge':       'token-badge',
  'transaction-row':   'transaction-row',
  'view':              'view',
  'wallet-address':    'wallet-address',
};
